# Generated by Django 5.1.2 on 2024-11-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_album_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
