# Generated by Django 5.1.2 on 2024-11-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_remove_song_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.PositiveIntegerField(default=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='streaming.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song History',
                'verbose_name_plural': 'Song Histories',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='streaming.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liked Song',
                'verbose_name_plural': 'Liked Songs',
                'unique_together': {('user', 'song')},
            },
        ),
    ]
