# Generated by Django 5.1.2 on 2025-01-11 09:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_remove_album_artist_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
