# Generated by Django 5.1.2 on 2025-01-11 09:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_alter_playlist_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='color',
            field=colorfield.fields.ColorField(default='#800080', image_field=None, max_length=25, samples=None),
        ),
    ]
